### ISSUE TITLE
Npm install Fails

### ISSUE THREAD

**Issue by QGaganSuneja** [vayser/react-js-pagination#106]
> node-sass@4.13.0 install /home/gagan/Documents/DAF_ONLINE_TRAINING/DFA_TRAINING_PROJECT/DEF_SOURCE_CODE/frontend/node_modules/node-sass
> node scripts/install.js

internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'mkdirp'
Require stack:
- /home/gagan/Documents/DAF_ONLINE_TRAINING/DFA_TRAINING_PROJECT/DEF_SOURCE_CODE/frontend/node_modules/node-sass/scripts/install.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gagan/Documents/DAF_ONLINE_TRAINING/DFA_TRAINING_PROJECT/DEF_SOURCE_CODE/frontend/node_modules/node-sass/scripts/install.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/gagan/Documents/DAF_ONLINE_TRAINING/DFA_TRAINING_PROJECT/DEF_SOURCE_CODE/frontend/node_modules/node-sass/scripts/install.js'
  ]
}
npm WARN dfa_traning_frontend@1.0.0 No description
npm WARN dfa_traning_frontend@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gagan/.npm/_logs/2020-04-17T19_28_50_862Z-debug.log

**Comment by QGaganSuneja** [comment]
After install mkdirp manually
It gives error for glob package
